---
- name: Morpheus create user 
  hosts: localhost
  gather_facts: yes
  vars: 
    morpheus_server: "{{ morpheus['morpheus']['applianceUrl'] }}"
    BEARER: "{{ morpheus['morpheus']['apiAccessToken'] }}"
    tenantId: "{{  morpheus['accountId'] }}"
    zoneId: "5"
    GroupID: "809"
  tasks:
    - name: Print result
      debug:
        var: BEARER
        
    - name: PUT to update zones
      uri:
        url: "{{ morpheus_server }}api/accounts/{{ tenantId }}/groups/{{ GroupID }}/update-zones"
        method: PUT
        headers:
          accept: "application/json"
          content-type: "application/json"
        body: |
          {
            "group": {
              "zones": [
                {
                  "id": {{ zoneId }}
                }
              ]
            }
          }
        body_format: json
        return_content: yes
        validate_certs: no
      register: result

    - name: Print result
      debug:
        var: result
