---
- name: Morpheus create user 
  hosts: localhost
  gather_facts: yes
  vars: 
    morpheus_server: "{{ morpheus['morpheus']['applianceUrl'] }}"
    BEARER: "{{ morpheus['morpheus']['apiAccessToken'] }}"
    tenantId: "{{  morpheus['accountId'] }}"

    URL: "172.16.10.178"
  tasks:
    - name: Create a group
      uri:
        url: "{{ morpheus_server }}api/groups"
        method: POST
        headers:
          Authorization: "Bearer {{ BEARER }}"
          Content-Type: "application/json"
        body: |
          {
            "group": {
              "name": "private_cloud"
            }
          }
        body_format: json
        return_content: yes
      register: result
    
    - name: Extract Group IDs
      set_fact:
        GroupID: "{{ response.json.group | map(attribute='id') | first }}"

    - name: Print result
      debug:
        var: GroupID
