- name: Add Worker node
  hosts: bastion
  vars_files:
    - vars/main.yml
  vars:
    # nodename: "{{  morpheus['customOptions']['nodename'] }}"
    ipaddr: "{{ morpheus['customOptions']['ipaddress'] }}"
    # kubeconfig: "{{ morpheus['customOptions']['kubeconfig'] }}"
    nodename: "{{  morpheus['customOptions']['nodename'] }}"
    cluster_name: "{{ morpheus['customOptions']['cluster_name'] }}"
    # nodename: "ocp4-compute-3"
    kubeconfig: "{{ ansible_env.HOME }}/{{ cluster_name }}/install-dir/auth/kubeconfig"
    # ipaddr: "192.168.9.51"
    # nodename: "ocp4-compute-4"
    # kubeconfig_path: '/root/lab/install-dir/auth/kubeconfig'

  tasks:
    - name: Get ignition_value file contents
      command: "cat {{ worker_node.ignition_file_path }}"
      register: ignition
    
    - name: set_fact the ignition_value
      set_fact:
        ignition_value: "{{ ignition.stdout }}"
        
    - name: Clone from openshift cluster
      vmware_guest:
        hostname: "{{ vcenter.host }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        validate_certs: no
        datacenter: "{{ vcenter.datacenter }}"
        folder: "{{ vcenter.folder }}"
        cluster: "{{ vcenter.cluster }}"
        template: "{{ openshift_template_name }}"
        #name: "{{ item.name }}.{{ openshift_cluster_name }}.{{ openshift_base_domain }}"
        name: "{{ nodename }}"
        state: "poweredoff"
        disk:
        - datastore: "{{ vcenter.default_datastore }}"
          type: "{{ worker_node.disk.type }}"
          size_gb: "{{ worker_node.disk.size | default(120) }}"
        hardware:
          memory_mb: "{{ worker_node.ram | default(16384) }}"
          memory_reservation_lock: true
          memory_reservation: "{{ bootstrap_node.ram }}"
          num_cpus: "{{ worker_node.cpus | default(4) }}"
        #networks:
        #- name: "{{ vcenter.network }}"
        wait_for_ip_address: no
        customvalues: 
          - key: "sched.cpu.latencySensitivity"
            value: "normal"
          - key: "guestinfo.afterburn.initrd.network-kargs"
            value: "ip={{ ipaddr }}::{{ vcenter.gateway }}:{{ vcenter.netmask }}:{{ nodename }}.{{ openshift_cluster_name }}.{{ openshift_base_domain }}:ens192:off:{{ vcenter.dns }}"               
          - key: "disk.EnableUUID"
            value: "TRUE"
          - key: "guestinfo.ignition.config.data.encoding"
            value: "base64"        
          - key: "guestinfo.ignition.config.data"
            value: "{{ ignition_value }}"
          #   value: "ip={{ IPaddress }}::{{ vcenter.gateway  }}:{{ vcenter.netmask }}:{{ item.name }}:none:{{ vcenter.dns  }}"

      
    - name: Configure network for worker nodes
      vmware_guest_network:
        hostname: "{{ vcenter.host }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        validate_certs: no
        name: "{{ nodename }}"
        networks:
          - name: "{{ vcenter.network }}"
            #manual_mac: "{{ item.macaddress }}"
            label: "Network adapter 1"
            state: present
            start_connected: true

    - name: Power-On the worker VMs
      vmware_guest:
        hostname: "{{ vcenter.host }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        validate_certs: no
        folder: "{{ vcenter.folder }}"
        name: "{{ nodename }}"
        state: poweredon
        
    - name: Wait for node-bootstraper csrs to approve
      shell: "{{ openshift_working_directory_path }}/bin/oc get csr -o json --kubeconfig={{ kubeconfig_path }} | jq -r '.items[] | select(.status == {}) | .metadata.name'" # noqa 301 306
      register: result_csr
      until: result_csr['stdout_lines']|count >= 1
      retries: 60
      delay: 60
      ignore_errors: true

    - name: Approve the csrs
      command: "{{ openshift_working_directory_path }}/bin/oc adm certificate approve {{ item }} --kubeconfig={{ kubeconfig_path }}" # noqa 301
      loop: "{{ result_csr['stdout_lines'] }}"
