- name: Delete worker node
  hosts: bastion
  vars_files:
    - vars/main.yml
  vars:
    # nodename: "{{  morpheus['customOptions']['nodename'] }}"
    # kubeconfig: "{{ morpheus['customOptions']['kubeconfig'] }}"
    nodename: "ocp4-compute-3"
    kubeconfig: '/root/lab/install-dir/auth/kubeconfig'
  tasks:
    - name: oc adm cordon 
      command: "oc adm cordon {{ nodename }}.{{ openshift_cluster_name }}.{{ openshift_base_domain }}"
      environment: 
        KUBECONFIG: "{{ kubeconfig }}"
      register: output
      ignore_errors: TRUE


    - name: oc adm drain
      command: "oc adm drain  {{ nodename }}.{{ openshift_cluster_name }}.{{ openshift_base_domain }} --ignore-daemonsets --delete-emptydir-data"
      environment: 
        KUBECONFIG: "{{ kubeconfig }}"
      register: output
      ignore_errors: TRUE

    - name: oc delete node
      command: "oc delete node  {{ nodename }}.{{ openshift_cluster_name }}.{{ openshift_base_domain }}"
      environment: 
        KUBECONFIG: "{{ kubeconfig }}"
      register: output
      ignore_errors: TRUE

    - name: Power-Off the openshift VMs
      vmware_guest:
        hostname: "{{ vcenter.host }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        validate_certs: no
        folder: "{{ vcenter.folder }}"
        name: "{{  nodename }}"
        state: poweredoff
       
    
    - name: Delete openshift VM
      vmware_guest:
        hostname: "{{ vcenter.host }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        validate_certs: no
        folder: "{{ vcenter.folder }}"
        name: "{{  nodename }}"
        state: absent
  
