---
- name: Generate the ignition 
  hosts: bastion
  vars_files:
    - vars/main.yml
  tasks: 
    - name: command 
      command: hostname 
      register: test 
    
    - debug:
        var: test