---
- name: Worker node Deployment
  hosts: bastion
  vars_files:
    - vars/main.yml
  tasks:         
    - name: Worker node Deployment
      include_role:
        name: master_worker_node
        tasks_from: worker_node.yml
