---
- name: Load data
  slurp:
    src: '/root/lab/install-dir/auth/kubeconfig'
  register: slurped_user_data
- name: Decode data and store as fact # You can skip this if you want to use the right hand side directly...
  set_fact:
    user_data: "{{ slurped_user_data.content | b64decode | to_yaml }}"
    
- name: Print returned information
  ansible.builtin.debug:
    msg: "{{ user_data }}"

- meta: end_play
    
- name: set_fact the ignition_value
  set_fact:
    #kubeconfig: "{{ kubeconfig.stdout }}"
    apiurl: "https://api.lab.ocp.local:6443"
    apitoken: "sha256~NMBoFU_G__YMxwk8a34MiUyeKbMj6xjuynryCwJBCrg"
    bearer_token: "c333e41e-5e89-41e1-94f4-87600bdab69e"
    
- debug:
    var: kubeconfig
    
- name: Create External kuberenets cluster
  uri:
    url:  https://morpheus-5-mgt.helionit.io/api/clusters
    method: post
    body_format: json
    # body:      
    #   "instance": 
    #     - ownerId: {{ owner_id }}
    body: |-
      { "cluster": { "type": "external-kubernetes-cluster",
      "group": {
        "id": 1143
      },
      "name": "{{ openshift_cluster_name }}" ,
      "cloud": {
        "id": 235
      },
      "layout": {
        "id": 251
      },
      "server": {
        "name":  "{{ openshift_cluster_name }}",
        "config": {
          "apiUrl": "{{ apiurl }}",
          "apiToken": "{{ apitoken }}",
          "serviceAccess": "{{ kubeconfig }}"
        },
        "plan": {
          "id": 113,
          "code": "external-default",
          "options": {
          }
        },
        "visibility": "private",
        "networkDomain": null,       
        }
        }
      }
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ bearer_token }}"
    return_content: true
    validate_certs: false
    status_code: 200
    timeout: 30
  register: webpage
