---
- name: Fetch Kubeconfig
  command: oc config view --raw  --kubeconfig={{ openshift_working_directory_path }}/install-dir/auth/kubeconfig
  register: kubeconfig_output

- name: Store Kubeconfig in a variable
  set_fact:
    kubeconfig: "{{ kubeconfig_output.stdout | regex_replace('\n', '')  }}"

- name: Fetch Kubeadmin Token
  shell: oc -n kube-system get secret kubeadmin -o jsonpath='{.data.token}' | base64 -d
  register: kubeadmin_token

- name: Print Kubeadmin Token
  debug:
    var: kubeadmin_token.stdout
    
- name: set_fact the ignition_value
  set_fact:
    #kubeconfig: "{{ kubeconfig.stdout }}"
    apiurl: "https://api.lab.ocp.local:6443"
    apitoken: "sha256~NMBoFU_G__YMxwk8a34MiUyeKbMj6xjuynryCwJBCrg"
    bearer_token: "c333e41e-5e89-41e1-94f4-87600bdab69e"
    
- debug:
    var: kubeconfig
    
- name: Create External kuberenets cluster
  uri:
    url:  https://morpheus-5-mgt.helionit.io/api/clusters
    method: post
    body_format: json
    # body:      
    #   "instance": 
    #     - ownerId: {{ owner_id }}
    body: |-
      { "cluster": { "type": "external-kubernetes-cluster",
      "group": {
        "id": 1143
      },
      "name": "{{ openshift_cluster_name }}" ,
      "cloud": {
        "id": 235
      },
      "layout": {
        "id": 251
      },
      "server": {
        "name":  "{{ openshift_cluster_name }}",
        "config": {
          "apiUrl": "{{ apiurl }}",
          "apiToken": "{{ apitoken }}",
          "serviceAccess": "{{ kubeconfig }}"
        },
        "plan": {
          "id": 113,
          "code": "external-default",
          "options": {
          }
        },
        "visibility": "private",
        "networkDomain": null,       
        }
        }
      }
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ bearer_token }}"
    return_content: true
    validate_certs: false
    status_code: 200
    timeout: 30
  register: webpage
